/control/verbose 1
/run/verbose 0
/event/verbose 0
/run/initialize
/ICESPICE/Detector/Thickness 100
/ICESPICE/Detector/Position -20
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g20mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -25
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g25mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -30
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g30mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -35
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g35mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -40
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g40mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -45
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g45mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -50
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g50mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -55
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g55mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -60
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS100_f50mm_g60mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Thickness 300
/ICESPICE/Detector/Position -20
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g20mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -25
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g25mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -30
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g30mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -35
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g35mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -40
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g40mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -45
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g45mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -50
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g50mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -55
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g55mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -60
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS300_f50mm_g60mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Thickness 500
/ICESPICE/Detector/Position -20
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g20mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -25
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g25mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -30
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g30mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -35
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g35mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -40
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g40mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -45
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g45mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -50
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g50mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -55
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g55mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -60
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS500_f50mm_g60mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Thickness 1000
/ICESPICE/Detector/Position -20
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g20mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -25
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g25mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -30
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g30mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -35
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g35mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -40
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g40mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -45
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g45mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -50
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g50mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -55
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g55mm_2000keV.root
/run/beamOn 10000
/ICESPICE/Detector/Position -60
/gun/energy 50 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_50keV.root
/run/beamOn 10000
/gun/energy 100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_100keV.root
/run/beamOn 10000
/gun/energy 150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_150keV.root
/run/beamOn 10000
/gun/energy 200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_200keV.root
/run/beamOn 10000
/gun/energy 250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_250keV.root
/run/beamOn 10000
/gun/energy 300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_300keV.root
/run/beamOn 10000
/gun/energy 350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_350keV.root
/run/beamOn 10000
/gun/energy 400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_400keV.root
/run/beamOn 10000
/gun/energy 450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_450keV.root
/run/beamOn 10000
/gun/energy 500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_500keV.root
/run/beamOn 10000
/gun/energy 550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_550keV.root
/run/beamOn 10000
/gun/energy 600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_600keV.root
/run/beamOn 10000
/gun/energy 650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_650keV.root
/run/beamOn 10000
/gun/energy 700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_700keV.root
/run/beamOn 10000
/gun/energy 750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_750keV.root
/run/beamOn 10000
/gun/energy 800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_800keV.root
/run/beamOn 10000
/gun/energy 850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_850keV.root
/run/beamOn 10000
/gun/energy 900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_900keV.root
/run/beamOn 10000
/gun/energy 950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_950keV.root
/run/beamOn 10000
/gun/energy 1000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1000keV.root
/run/beamOn 10000
/gun/energy 1050 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1050keV.root
/run/beamOn 10000
/gun/energy 1100 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1100keV.root
/run/beamOn 10000
/gun/energy 1150 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1150keV.root
/run/beamOn 10000
/gun/energy 1200 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1200keV.root
/run/beamOn 10000
/gun/energy 1250 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1250keV.root
/run/beamOn 10000
/gun/energy 1300 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1300keV.root
/run/beamOn 10000
/gun/energy 1350 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1350keV.root
/run/beamOn 10000
/gun/energy 1400 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1400keV.root
/run/beamOn 10000
/gun/energy 1450 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1450keV.root
/run/beamOn 10000
/gun/energy 1500 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1500keV.root
/run/beamOn 10000
/gun/energy 1550 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1550keV.root
/run/beamOn 10000
/gun/energy 1600 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1600keV.root
/run/beamOn 10000
/gun/energy 1650 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1650keV.root
/run/beamOn 10000
/gun/energy 1700 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1700keV.root
/run/beamOn 10000
/gun/energy 1750 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1750keV.root
/run/beamOn 10000
/gun/energy 1800 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1800keV.root
/run/beamOn 10000
/gun/energy 1850 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1850keV.root
/run/beamOn 10000
/gun/energy 1900 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1900keV.root
/run/beamOn 10000
/gun/energy 1950 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_1950keV.root
/run/beamOn 10000
/gun/energy 2000 keV
/analysis/setFileName ICESPICE_PIPS1000_f50mm_g60mm_2000keV.root
/run/beamOn 10000
